services:
  - type: web
    name: cs5131lab01-mosaic
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: GRADIO_SSR_MODE
        value: "false"
